### ISSUE TITLE
Do I need to modify the some parameters to recognize 10 to 20 characters?

### ISSUE THREAD

**Issue by lindadamama** [williamlzw/MicroOCR.NET#3]
I found that in this project, the accuracy of identifying 1 to 4 characters at one time is relatively high. If the number of characters increases, no matter how you train, the output results will have more problems.

**Comment by williamlzw** [comment]
I train simple samples of 10 to 20 characters here, and 10,000 samples only need 2 epochs to get 99% accuracy. Is it convenient to send your sample pictures to see?

**Comment by williamlzw** [comment]
![image](https://github.com/williamlzw/MicroOCR.NET/assets/11348670/63bbb156-e222-4042-b181-09173836b322)

**Comment by williamlzw** [comment]
Try changing NH to 256 or 512

**Comment by lindadamama** [comment]
[dataset.zip](https://github.com/williamlzw/MicroOCR.NET/files/12571369/dataset.zip)
[english.zip](https://github.com/williamlzw/MicroOCR.NET/files/12571384/english.zip)
My data set has never achieved the training effect.I try changing NH to 256 ,512 and 1024

**Comment by williamlzw** [comment]
[MicroOcr_nh64_depth2_epoch20_wordAcc0.9167_charAcc0.9882.zip](https://github.com/williamlzw/MicroOCR.NET/files/12571798/MicroOcr_nh64_depth2_epoch20_wordAcc0.9167_charAcc0.9882.zip)
I trained for 20 epochs and the verification accuracy was 91%.

**Comment by williamlzw** [comment]
[MicroOcr_nh64_depth2_epoch5_wordAcc1.0000_charAcc1.0000.zip](https://github.com/williamlzw/MicroOCR.NET/files/12571831/MicroOcr_nh64_depth2_epoch5_wordAcc1.0000_charAcc1.0000.zip)

I trained for 23 epochs and the verification accuracy was 100%.

**Comment by williamlzw** [comment]
![image](https://github.com/williamlzw/MicroOCR.NET/assets/11348670/97114f2f-f84e-4a02-8b56-1d4958438d7f)

**Comment by lindadamama** [comment]
I downloaded a new copy of the code and tried it out, and it worked as expected

**Comment by williamlzw** [comment]
Upload your code so I can take a look.
